#!/usr/bin/env python3

print("Content-Type: text/html\r")
print("\r")
print("<html>")
print("<head><title>CGI Test</title></head>")
print("<body style='font-family: monospace; background: #1e1e1e; color: #00ff00; padding: 50px;'>")
print("<h1>✓ CGI Script Working!</h1>")
print("<p>This page was generated by a Python CGI script.</p>")
print("<p><strong>Server Environment:</strong></p>")
print("<ul>")

import os
for key in ['REQUEST_METHOD', 'QUERY_STRING', 'CONTENT_TYPE', 'CONTENT_LENGTH']:
    value = os.environ.get(key, 'Not set')
    print(f"<li>{key}: {value}</li>")

print("</ul>")
print("<p><a href='/' style='color: #00aaff;'>← Back to Home</a></p>")
print("</body>")
print("</html>")
